### ISSUE TITLE
Aliases are expanded

### ISSUE THREAD

**Issue by sjakobi** [sjakobi/haddock#6]
In `microlens` we currently generate

![image](https://user-images.githubusercontent.com/3664523/42758724-bae7ef5a-8904-11e8-9a0a-cc9748332591.png)

for what should be

![image](https://user-images.githubusercontent.com/3664523/42758783-f0ed10da-8904-11e8-9002-7c95fde17f73.png)

**Comment by sjakobi** [comment]
Surprisingly, the `.hi`-files seem to use the alias we want:

```
_Right :: Traversal (Either a b) (Either a b') b b'
```

**Comment by alexbiehl** [comment]
Is this from show-hi?

Simon Jakobi <notifications@github.com> schrieb am Mo., 16. Juli 2018,
14:48:

**Comment by alexbiehl** [comment]
Maybe something is expanding type synonyms in haddock.

**Comment by sjakobi** [comment]
> Is this from show-hi?

That's how `--show-iface` dumps the `.hi`-file.

**Comment by sjakobi** [comment]
Using `hiDecl` instead of generating the `HsDecl` in `mkDeclMap` doesn't seem to have caused this issue.

**Comment by sjakobi** [comment]
The problem seems to be somewhere in `tyThingToLHsDecl`. The `TyThing` we find in `hiDecl` still has the alias according to `pprTyThing showToIface`.

**Comment by sjakobi** [comment]
Aliases aren't expanded in every case:

```
{-# language RankNTypes #-}
module Lib where

type Traversal s t a b = forall f. Applicative f => (a -> f b) -> s -> f t

-- Fails
_Right :: Traversal (Either a b) (Either a b') b b'
_Right f (Right b) = Right <$> f b
_Right _ (Left a) = pure (Left a)

type Unit = ()

-- Works
x :: Unit
x = ()
```

**Comment by RyanGlScott** [comment]
Ugh, I know why this is happening. It's due to these lines in `synifyType`:

https://github.com/haskell/haddock/blob/4abf7d4979b5364da59f7412a3d7143aea26cf7e/haddock-api/src/Haddock/Convert.hs#L517-L520

In particular, this calls [`tcSplitSigmaTy`](http://git.haskell.org/ghc.git/blob/8b6a9e5575fc848dc03b50b415aa57447654662f:/compiler/typecheck/TcType.hs#l1566), which in turn invokes two functions ([`splitForAllTys`](http://git.haskell.org/ghc.git/blob/71f6b18ba365da9ee4795f6cbce6ec9f1bfe95e8:/compiler/types/Type.hs#l1316) and [`tcSplitPredFunTy_maybe`](http://git.haskell.org/ghc.git/blob/71f6b18ba365da9ee4795f6cbce6ec9f1bfe95e8:/compiler/typecheck/TcType.hs#l1547)) that expand type synonyms. This also explains why this doesn't affect `type Unit = ()`, as this code is only ever called for types with a `forall` at the front.

I'm not sure of a way to work around this other than developing a counterpart to `tcSplitSigmaTy` that doesn't expand type synonyms...

**Comment by sjakobi** [comment]
Let's discuss this further at https://github.com/haskell/haddock/issues/879.
